(TeX-add-style-hook "universal3"
 (lambda ()
    (LaTeX-add-index-entries
     "Coret"
     "G\\\"odel"
     "Specker"
     "Quine"
     "Boffa"
     "GC"
     "involution"
     "$J_n$"
     "NF3")
    (LaTeX-add-labels
     "quineatomtau"
     "dominateTinverse"
     "corollequal"
     "lem:trans"
     "rem:twiddle"
     "plus"
     "rank1"
     "lem:weakhenson"
     "rembottomlesssetsofpowersets"
     "A message from Richard Kaye"
     "infinite rank"
     "thm:tarski"
     "lem:bert"
     "thm:elemequiv"
     "thm:q2q3"
     "thm:initialextension"
     "thm:gamma1"
     "thm:gamma2"
     "wellfounded"
     "conj:universalexistential1"
     "conj:universalexistential2"
     "conj:universalexistential3"
     "conj:universalexistential4"
     "conj:universalexistential5"
     "henkin"
     "ref:boffapermutation"
     "conj:boffa1"
     "rem:metaboffa"
     "rem:small"
     "history"
     "rem:verysim1"
     "rem:verysim2"
     "prop:four"
     "prop:five"
     "thm:angus"
     "angus2"
     "another"
     "eqnscheme"
     "next"
     "prop1.1"
     "coroll1.2"
     "coroll1.3"
     "prop2.3"
     "prop2.4"
     "prop2.5"
     "prop2.7"
     "lemmanathan"
     "corolldisj"
     "remdouble"
     "firstC"
     "CCCC"
     "small"
     "one"
     "end-extension"
     "Natural models"
     "Other models"
     "conj:generalhierarchy"
     "Some remarks on permutations and bijections"
     "approx"
     "equidecomposable"
     "GCdef"
     "prop:``existence of permutations\""
     "thm:"
     "thm:termauto")
    (TeX-add-symbols
     "ZZ")
    (TeX-run-style-hooks
     "boxedminipage"
     "amssymb"
     "amsfonts"
     "amsmath"
     "amsbsy"
     "epsfig"
     "bussproofs"
     "graphicx"
     "latexsym"
     "latex2e"
     "bk10"
     "book"
     "a4"
     "10pt"
     "newlogicmacr")))

